# Disable built-in rules
MAKEFLAGS += -rR

AS = $(CROSS_COMPILE)as
LD = $(CROSS_COMPILE)ld
CC = $(CROSS_COMPILE)gcc
ifeq ($(BIT32),y)
  CFLAGS += -Wall -m32 -I$(CURDIR) -I$(COMMON_DIR)
else
  CFLAGS += -Wall -m64 -I$(CURDIR) -I$(COMMON_DIR)
endif

ifdef DEBUG
  CFLAGS += -g -DDEBUG
else
  CFLAGS += -O2
endif
