# Disable built-in rules
MAKEFLAGS += -rR

AS = $(CROSS_COMPILE)as
AR = $(CROSS_COMPILE)ar
LD = $(CROSS_COMPILE)ld
CC = $(CROSS_COMPILE)gcc
CFLAGS += -Wall -Wunused-but-set-variable -O2 -g -I$(CURDIR) -I$(COMMON_DIR) -fPIC
ifeq ($(BIT32),y)
  CFLAGS += -m32
else
  CFLAGS += -m64
endif

ifdef DEBUG
 CFLAGS += -pg -DDEBUG
endif
