# Disable built-in rules
MAKEFLAGS += -rR

AS = $(CROSS_COMPILE)as
AR = $(CROSS_COMPILE)ar
LD = $(CROSS_COMPILE)ld
CC = $(CROSS_COMPILE)gcc
ifeq ($(BIT32),y)
  CFLAGS += -g -Wall -O2 -m32 -I$(CURDIR) -Iinclude -I$(COMMON_DIR) -fPIC
else
  CFLAGS += -g -Wall -O2 -m64 -I$(CURDIR) -Iinclude -I$(COMMON_DIR) -fPIC
endif

ifdef DEBUG
  CFLAGS += -DDEBUG
endif
