# Disable built-in rules
MAKEFLAGS += -rR

AS = $(CROSS_COMPILE)as
LD = $(CROSS_COMPILE)ld
CC = $(CROSS_COMPILE)gcc
CFLAGS += -Wall -I$(CURDIR) -I$(COMMON_DIR)
ifeq ($(BIT32),y)
  CFLAGS += -m32
else
  CFLAGS += -m64
endif

ifdef DEBUG
  CFLAGS += -g -pg -DDEBUG
else
  CFLAGS += -O2
endif
