# Disable built-in rules
MAKEFLAGS += -rR

AS = $(CROSS_COMPILE)as
LD = $(CROSS_COMPILE)ld
CC = $(CROSS_COMPILE)gcc
CPP = $(CROSS_COMPILE)g++
CFLAGS += -Wall -I$(CURDIR) -I$(COMMON_DIR)

ifeq ($(BIT32),y)
  CFLAGS += -m32
else
  CFLAGS += -m64
endif

ifdef DEBUG
  CFLAGS += -g -pg -DDEBUG
else
  CFLAGS += -O2
endif

ifeq ($(PSLVER),8)
  CFLAGS += -DPSL8
else
ifeq ($(PSLVER), 9)
  CFLAGS += -DPSL9
else
ifeq ($(PSLVER), D)
  CFLAGS += -DPSL9 -DPSL9D
else
  $(error Must set PSLVER to 8 for PSL8 sim; to 9 for full PSL9 sim; to D for PSL9 sim w/o Buffer Interface)
endif
endif
endif
