# Disable built-in rules
MAKEFLAGS += -rR

AS = $(CROSS_COMPILE)as
AR = $(CROSS_COMPILE)ar
LD = $(CROSS_COMPILE)ld
CC = $(CROSS_COMPILE)gcc
CFLAGS += -Wall -I$(CURDIR) -I$(COMMON_DIR) -I$(LIBCXL_DIR) -fPIC
LINKFILES = TestAFU_config.o $(LIBCXL_DIR)/libcxl.a

ifeq ($(BIT32),y)
  CFLAGS += -m32
else
  CFLAGS += -m64
endif

ifdef DEBUG
 CFLAGS += -pg -g -DDEBUG
else
 CFLAGS += -O2
endif
