# Disable built-in rules
MAKEFLAGS += -rR

AS = $(CROSS_COMPILE)as
LD = $(CROSS_COMPILE)ld
CC = $(CROSS_COMPILE)gcc
CFLAGS += -Wall -Wunused-but-set-variable -I$(CURDIR) -fPIC
ifeq ($(BIT32),y)
  CFLAGS += -m32
  LINK_FLAGS=-shared -m32
else
  CFLAGS += -m64
  LINK_FLAGS=-shared
endif

ifdef DEBUG
  CFLAGS += -g -pg -DDEBUG
else
  CFLAGS += -O2
endif

ifdef FINISH
  CFLAGS += -DFINISH
endif
